---
title: "dge"
author: "Jordan Lee"
date: "2/28/2020"
output: html_document
---

This is a html version of dge.R as of end of day 2/28/20

```{r}
# Disclaimer: hardcoded names of patients in flat_matrix
# hard coded condition vector
####################
file_bulk <-'/Users/leejor/Ellrott_Lab/04_CSBC/cell-dissociation/data/01_process-bulkrna/07_ct_matrices/TESTDATA--UHR_Rep1_ERCC-Mix1_Build37-ErccTranscripts-chr22_COUNTmatrix.txt'
countsMECH_1_matrix_dir <- '/Users/leejor/Ellrott_Lab/04_CSBC/cell-dissociation/data/02_process-scrna/7319_Mech/'
countsENZ_1_matrix_dir <- '/Users/leejor/Ellrott_Lab/04_CSBC/cell-dissociation/data/02_process-scrna/7319_Enz/'
countsMECH_2_matrix_dir <- '/Users/leejor/Ellrott_Lab/04_CSBC/cell-dissociation/data/02_process-scrna/7319_Mech/'
countsENZ_2_matrix_dir <- '/Users/leejor/Ellrott_Lab/04_CSBC/cell-dissociation/data/02_process-scrna/7319_Enz/'
THRES = 0.1
output_sortedGenes = '/Users/leejor/Ellrott_Lab/04_CSBC/cell-dissociation/data/03_compare-bulk_scrna/scrna2bulk/geneOrdered_results.csv'
####################
```

```{r, message=FALSE}
library(Seurat)
library(dplyr)
library(Matrix)
library(gdata)
library(DESeq2)
library(ggplot2)
library(pheatmap)
library(vsn)
library(RColorBrewer)
```

```{r}
###############################
# Create combined count matrices
###############################
# Read in files
counts_mech1 <- Read10X(data.dir = countsMECH_1_matrix_dir)
counts_enz1 <- Read10X(data.dir = countsENZ_1_matrix_dir)
counts_mech2 <- Read10X(data.dir = countsMECH_2_matrix_dir)
counts_enz2 <- Read10X(data.dir = countsENZ_2_matrix_dir)

# convert to dense matrix
counts_mech1 <- as.matrix(counts_mech1) 
counts_enz1 <- as.matrix(counts_enz1) 
counts_mech2 <- as.matrix(counts_mech2) 
counts_enz2 <- as.matrix(counts_enz2) 


######## Subset for testing ###########
# # counts_mech1 <- counts_mech1[256:260, 1:3]
# counts_mech1 <- counts_mech1[493:498, 1:3]
# counts_mech1
# counts_enz1 <- counts_enz1[493:498, 1:3]
# counts_enz1
# counts_mech2 <- counts_mech2[493:498, 1:3]
# counts_mech2
# counts_enz2 <- counts_enz2[493:498, 1:3]
# counts_enz2
#######################################

# Flaten counts (sum all cells for a gene) + combine matrices
mech1 <- c(rowSums(counts_mech1)) 
enz1 <- c(rowSums(counts_enz1)) 
mech2 <- c(rowSums(counts_mech2)) 
enz2 <- c(rowSums(counts_enz2)) 

############# need replicates so randomize, but in real use second and third datasetes
set.seed(10)
mech2 <- sample(mech2)
# mech2
enz2 <- sample(enz2)
# enz2
#######################################


flat_matrix <- cbind('mech-7319'=mech1, 'mech-7320'=mech2, 'enz-7319'=enz1,'enz-7320'=enz2)
# flat_matrix

############################
# Create meta data table of which samples are which treatment - needed for Deseq2
#############################
# Grab samples in order
samples <- colnames(flat_matrix)
# samples
# Create condition vector and type
condition <- c('mech','mech', 'enz', 'enz')
# type <- c('paried-end','paried-end')
# meta_data <- as.data.frame(cbind(condition, type) )
meta_data <- as.data.frame(condition)
rownames(meta_data) <- samples
# meta_data

#####################
# DGE
#####################
# Remove gene rows that are not expressed in any samples
flat_matrix <- flat_matrix[rowSums(flat_matrix > 0) != 0, ] 
dds <- DESeqDataSetFromMatrix(countData = flat_matrix, colData = meta_data, design = ~ condition)
dds <- DESeq(dds)
res <- results(dds, alpha=THRES)
( mcols(res)$description ) # info

###################
# Visuals and a few downstream analysis
###################
# 1. explore diff shrinking methods
    # Shrink logfoldchange - remove noise + more conserv + tend to align closer to trends in larger sample sizes
( resultsNames(dds) )
resLFC <- lfcShrink(dds, coef="condition_mech_vs_enz", type="apeglm")
resNorm <- lfcShrink(dds, coef="condition_mech_vs_enz", type="normal")
resAsh <- lfcShrink(dds, coef="condition_mech_vs_enz", type="ashr")

par(mfrow=c(2,2), mar=c(4,4,2,1))
xlim <- c(1,1e5); ylim <- c(-3,3)
plotMA(res, main='no shrinking')
plotMA(resLFC, main="apeglm")
plotMA(resNorm, main="normal")
plotMA(resAsh, main="ashr")
#dev.off()

# 2. explore read count for ONE gene across groups
d <- plotCounts(dds, gene=which.min(res$padj), intgroup="condition", returnData=TRUE) #which.min return index of smallest pval gene
ggplot(d, aes(x=condition, y=count)) + 
  geom_point(position=position_jitter(w=0.1,h=0)) + 
  scale_y_log10(breaks=c(25,100,400))

# 3. Top diff exp genes
# Sort by most signfi diff (adj pval)
resOrdered <- res[order(res$padj),]
( summary(resOrdered) )
write.csv(as.data.frame(resOrdered), file=output_sortedGenes)    
# Subset for only signficant genes
resSig <- subset(resOrdered, padj < THRES)
print('Number of signficant genes and alpha:')
( sum(resOrdered$padj < THRES, na.rm=TRUE) )
# resSig




#################
# heatmap of normalized and transformed 
##################
select <- order(rowMeans(counts(dds,normalized=TRUE)), decreasing=TRUE)[1:40] #top 40 

# Transform 1: 
ntd <- normTransform(dds)
meanSdPlot(assay(ntd)) #visual of this transformation
select <- order(rowMeans(counts(dds,normalized=TRUE)), decreasing=TRUE)[1:40] #top 40 
pheatmap(assay(ntd)[select,], cluster_rows=FALSE, show_rownames=FALSE, cluster_cols=FALSE)

# Transform 2: 
vsd <- vst(dds, blind=FALSE)
meanSdPlot(assay(ntd)) #visual of this transformation
pheatmap(assay(vsd)[select,], cluster_rows=FALSE, show_rownames=FALSE, cluster_cols=FALSE)

# Transform 3: 
rld <- rlog(dds, blind=FALSE)
meanSdPlot(assay(ntd)) #visual of this transformation
pheatmap(assay(rld)[select,], cluster_rows=FALSE, show_rownames=FALSE, cluster_cols=FALSE)


#############
# Sample clustering - do we see samples from the same treatment grouping together
  # using vsd for now
############
sampleDists <- dist(t(assay(vsd)))
sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- paste(vsd$condition, sep="-")
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors)


###############
# PCA 
  # using vsd for now 
##############
plotPCA(vsd, intgroup=c("condition"))
```